### ISSUE TITLE
support creating a Transaction without sending

### ISSUE THREAD

**Issue by ilanDoron** [tranvictor/jarvis#3]
Sometimes need to create transaction data for sending with etherscan (&metamask) or other tool
at the moment I write a web3 script to encode the Tx.

Requesting jarvis to build and encode transaction without sending.
output as data string to screen or saving in file.

**Comment by tranvictor** [comment]
the feature is added at 4eccb335c52f1e145d3e1b69c68a4eb9a7a28960
